version: '3.7'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        # https://medium.com/faun/set-current-host-user-for-docker-container-4e521cef9ffc
        # export UID=$(id -u)
        # export GID=$(id -g
        # user: $UID:$GID
        environment: 
            - SECRET_KEY=k!fng(h=p&b9=!f^u)%_x6mkpve5=)tx^f_h6sg=-9jsdhf)q3
            - DEBUG=1
            # - "DJANGO_DEBUG=True"
            # - "DJANGO_SECRET_KEY=k!fng(h=p&b9=!f^u)%_x6mkpve5=)tx^f_h6sg=-9jsdhf)q3"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        environment: 
            # без указания пороля не стартует DB
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data/

# подключаем том для Postgresql
volumes: 
    postgres_data: